Processing date: 2024-05-28 19:05:01.470313-03:00
Traceback (most recent call last):
  File "stsc/stsc2mongo.py", line 110, in <module>
    main()
  File "stsc/stsc2mongo.py", line 91, in main
    trata_stsc(l_mcli)
  File "stsc/stsc2mongo.py", line 64, in trata_stsc
    print("Processing size:", len(ldct_stsc["stsc"][0]))
IndexError: list index out of range
